exports.tekscmd =["Command tidak ditemukan","Maaf kak command tidak di temukan","Gak ada","Command tidak tersedia",
"Apaan tuh ? 🙄",
"Maap kak ga ada dalam menu ☹️",
"Yang bener atuh kak ketiknya 🙄",
"Yang bener nulisnya bambang 🤨",
"Engga ada kak 🙃",
"Auah kaka bau","Salah ketik itu kak 😮",
"Kaka ngetik apasih aku ga ngerti 🥺","Oke kak aku proses yah, proses gundulmu ga ada itu dalam menu 😒",
"Ngetiknya yang bener dong 😠",
"Enggak mau 🙁","Enggak ah","Berantem yuk 😤","Berantem yuk maju sini 😠","Aku ga mau jawab 😤",
"Hmm apa yah ga tau aku 🤤",
"Ga tau aku kan ikan 😎",
"Hadehh 😑","Maap kaka yang ganteng aku ga tau 🥺","Maap kaka yang cantik aku ga tau 🥺",
"Muke lu ke gorengan 🤤","Enggak ketemu kak 😥",
"Yo ndak tau kok tanya saya 😅",
"Macam tak betul budak ni 😑",
"Ih apasih ga jelas banget kek admin, hehe camda 😅",
"Waduh apaan tuh kak 🙄","Sedang di proses silakan tunggu 3 jam lagi",
"Gak ada 🙂","Mana saya tau, sayakan ga tau 🙁","Berhenti jangan mainin aku kak 😥",
"Waduh klo itu saya tidak bisa 😳",
"Eh salah bukan itu 😥","Bukan itu bambang","Lagi berak🤭","Lagi di tandas🤭"]